version: "3"
services:

  eosio:
    image: eosio/eos:dawn3x
    ports:
      - "8888:8888"
      - "9876:9876"
    command: /opt/eosio/bin/nodeosd.sh --resync-blockchain
    volumes:
      - ./eosio-volume/config:/opt/eosio/bin/data-dir
      - ./eosio-volume/data:/opt/eosio/var
    logging:
      driver: none

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    links:
      - eosio
    volumes:
      - ./:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:

  data:
